from pptx.util import Pt
from pptx.dml.color import RGBColor

THEMES = {
    "business": {
        "name": "비즈니스",
        "cover_bg": RGBColor(0x00, 0x1D, 0x2C),
        "content_bg": RGBColor(0xF2, 0xF2, 0xF2),
        "title_color_light": RGBColor(0xFF, 0xFF, 0xFF),
        "title_color_dark": RGBColor(0x22, 0x22, 0x22),
        "text_color": RGBColor(0x33, 0x33, 0x33),
        "accent_color": RGBColor(0x44, 0x54, 0x6A),
        "subtitle_color": RGBColor(0xBB, 0xBB, 0xBB),
        "divider_color": RGBColor(0xFF, 0xFF, 0xFF),
        "bullet_color": RGBColor(0x44, 0x72, 0xC4),
        "heading_bg": RGBColor(0x44, 0x54, 0x6A),
        "title_font": "맑은 고딕",
        "body_font": "맑은 고딕",
        "cover_title_size": Pt(40),
        "cover_subtitle_size": Pt(14),
        "heading_size": Pt(20),
        "body_size": Pt(14),
        "small_size": Pt(10),
        "caption_size": Pt(15),
    },
    "simple": {
        "name": "심플",
        "cover_bg": RGBColor(0x1A, 0x1A, 0x2E),
        "content_bg": RGBColor(0xFF, 0xFF, 0xFF),
        "title_color_light": RGBColor(0xFF, 0xFF, 0xFF),
        "title_color_dark": RGBColor(0x1A, 0x1A, 0x2E),
        "text_color": RGBColor(0x44, 0x44, 0x44),
        "accent_color": RGBColor(0x1A, 0x1A, 0x2E),
        "subtitle_color": RGBColor(0xAA, 0xAA, 0xAA),
        "divider_color": RGBColor(0xFF, 0xFF, 0xFF),
        "bullet_color": RGBColor(0x1A, 0x1A, 0x2E),
        "heading_bg": RGBColor(0x1A, 0x1A, 0x2E),
        "title_font": "맑은 고딕",
        "body_font": "맑은 고딕",
        "cover_title_size": Pt(40),
        "cover_subtitle_size": Pt(14),
        "heading_size": Pt(20),
        "body_size": Pt(14),
        "small_size": Pt(10),
        "caption_size": Pt(15),
    },
    "dark": {
        "name": "다크",
        "cover_bg": RGBColor(0x0A, 0x0A, 0x0A),
        "content_bg": RGBColor(0x1E, 0x1E, 0x1E),
        "title_color_light": RGBColor(0xFF, 0xFF, 0xFF),
        "title_color_dark": RGBColor(0xFF, 0xFF, 0xFF),
        "text_color": RGBColor(0xDD, 0xDD, 0xDD),
        "accent_color": RGBColor(0x00, 0xBC, 0xD4),
        "subtitle_color": RGBColor(0x88, 0x88, 0x88),
        "divider_color": RGBColor(0x00, 0xBC, 0xD4),
        "bullet_color": RGBColor(0x00, 0xBC, 0xD4),
        "heading_bg": RGBColor(0x2D, 0x2D, 0x2D),
        "title_font": "맑은 고딕",
        "body_font": "맑은 고딕",
        "cover_title_size": Pt(40),
        "cover_subtitle_size": Pt(14),
        "heading_size": Pt(20),
        "body_size": Pt(14),
        "small_size": Pt(10),
        "caption_size": Pt(15),
    },
}


def get_theme(name: str) -> dict:
    return THEMES.get(name, THEMES["business"])
